services:
  web:
    build:
      context: .
      args:
        - BASE_URL=https://clothbird.reankhode.com
    container_name: clothbird_front
    ports:
      - "3001:3000"
    # You still need this for the runtime container
    environment:
      - BASE_URL=https://clothbird.reankhode.com
    volumes:
      - .:/usr/src/app
    restart: always